### ISSUE TITLE
Improve Exception outputHandling

### ISSUE THREAD

**Issue by WernerMairl** [wkallhof/iron-beard#4]
Hi
really nice tool - i'm starting a evaluation process for my new community homepage!
this (and the following issues) are my current contribution to this project... ;-)

----------------------------
the following code should be improved.
my usecase: e.message does not contains "tempFile.FullPath" means file name is not injected in the error message, that's painful.....
expected behavior:

file name should be part of the exception message in every case....

```
            catch(Exception e)
            {
                // there was a problem, likely a razor formatting issues or issue with our
                // renderer not finding the view file. In the event the issue with a problem with our
                // razor syntax, make sure we replace the temp file path with the original path so the user
                // knows where to find the syntax error.
                var message = e.Message.Replace(tempFile.FullPath, file.FullPath);
                throw new Exception(message);
            }
```

regards
Werner

**Comment by wkallhof** [comment]
I completely agree @WernerMairl , I updated the error handling to always include the `file.FullPath` in the message in this commit 5d57cf5e71461079b777723c5a3bac064a6c4186
